(function(M,e,a,P){"use strict";const f=[];var u={patch:l=>l&&f.push(l),unpatchAll:()=>f.forEach(l=>l()),lazyPatchContextMenu:async(l,t)=>{const i=s=>s.default&&s.default.displayName===l,r=a.find(i,!1);if(r)t(r);else{const s=a.findByProps("openContextMenuLazy");f.unshift(before("openContextMenuLazy",s,n=>{const c=n[1];return n[1]=async()=>{const o=await c(n[0]);return B=>{const R=o(B);return R?.type?.displayName===l&&t&&(unpatch[0](),t(a.find(i)),t=!1),R}},n}))}}};/**
* NOTICE OF LICENSE
*
* This source file is subject to the GNU General Public License (GPL-3.0).
* You can find more information in the LICENSE.md file.
* More information is also avaliable at this URL:
* https://opensource.org/licenses/GPL-3.0
*
*
* @copyright Copyright (c) 2022 Paige Jordan
* @license   GPL-3.0 GNU General Public License v3.0
* @link      https://github.com/swishs-client-mod-plugins/cumcord-plugins/tree/main/plugins/permission-viewer
*/const C=a.findByDisplayName("Flex"),I=a.findByDisplayName("Text"),y=a.findByDisplayName("TabBar"),g=a.findByDisplayName("Close"),D=a.findByDisplayName("Checkmark"),E=a.findByProps("ModalCloseButton"),{Permissions:d}=e.constants,h={TabBar:a.findByProps("tabBarContainer"),ReactionModal:a.findByProps("spinnerMore"),RoleMenu:a.findByProps("roleDot","sidebar")};var m=({event:l,roles:t={},permissions:i})=>{const[r,s]=e.React.useState(Object.keys(t)[0]);return e.React.createElement(E.ModalRoot,{transitionState:l.transitionState,className:h.ReactionModal.container,size:"large"},e.React.createElement(P.ErrorBoundary,null,i||e.React.createElement(E.ModalContent,null,e.React.createElement(y,{selectedItem:r,type:y.Types.SIDE,onItemSelect:s},Object.keys(t).map(n=>e.React.createElement(y.Item,{id:t[n].id,className:h.RoleMenu.row,itemType:y.Types.SIDE},e.React.createElement("div",{className:h.RoleMenu.roleDot,style:{backgroundColor:t[n].colorString||"#99aab5"}}),e.React.createElement(I,{className:h.RoleMenu.roleName},t[n].name))))),e.React.createElement(E.ModalContent,null,Object.keys(d).map(n=>{const c=r?t[r].permissions:i,o=t?.[r]?.permissionsDeny,B=(c&d.ADMINISTRATOR)===d.ADMINISTRATOR;return e.React.createElement(C,{style:{paddingLeft:"12px",paddingRight:"264px"},align:"alignCenter-14kD11",className:"reactorDefault-3GSyaV reactor-1J25Qp"},e.React.createElement(C.Child,{grow:0,shrink:0},(c&d[n])===d[n]&&(o?(o&d[n])!==d[n]:!0)||B?e.React.createElement(D,{className:!0,height:24,width:24,color:"#43B581"}):e.React.createElement(g,{height:24,width:24,color:"#F04747"})),e.React.createElement(C.Child,null,e.React.createElement(I,null,n.charAt(0).toUpperCase()+n.slice(1).toLowerCase().replace(/_\w/g,R=>" "+R.toUpperCase().slice(1)))))}))))};/**
* NOTICE OF LICENSE
*
* This source file is subject to the GNU General Public License (GPL-3.0).
* You can find more information in the LICENSE.md file.
* More information is also avaliable at this URL:
* https://opensource.org/licenses/GPL-3.0
*
*
* @copyright Copyright (c) 2022 Paige Jordan
* @license   GPL-3.0 GNU General Public License v3.0
* @link      https://github.com/swishs-client-mod-plugins/cumcord-plugins/tree/main/plugins/permission-viewer
*/const p=a.findByProps("MenuGroup","MenuItem"),{Permissions:N}=e.constants,{getGuild:O}=a.findByProps("getGuild"),{getMember:T}=a.findByProps("getMember"),{openModal:x}=a.findByProps("openModal","openModalLazy"),S=()=>{u.lazyPatchContextMenu("GuildContextMenu",l=>{u.patch(M.after("default",l,([t],i)=>(i?.props?.children?.splice(1,0,e.React.createElement(e.React.Fragment,null,e.React.createElement(p.MenuSeparator,null),e.React.createElement(p.MenuItem,{label:"View Permissions",id:"permissions",action:()=>{x(r=>e.React.createElement(m,{event:r,roles:t.guild.roles}))}}))),i)))})},L=()=>{u.lazyPatchContextMenu("GuildChannelUserContextMenu",l=>{u.patch(M.after("default",l,([t],i)=>{const r=O(t.guildId),s=T(t.guildId,t.user.id),n=r.ownerId===t.user.id?Object.values(N).reduce((c,o)=>c|o,0n):Object.values(r.roles).reduce((c,o)=>~s.roles.indexOf(o.id)?c|o.permissions:c,0n|r.roles[t.guildId].permissions);return i?.props?.children?.props?.children?.splice(2,0,e.React.createElement(e.React.Fragment,null,e.React.createElement(p.MenuSeparator,null),e.React.createElement(p.MenuItem,{label:"View Permissions",id:"permissions",action:()=>{x(c=>e.React.createElement(m,{event:c,permissions:n}))}}))),i}))})},v=()=>{const l=a.find(t=>t.default?.displayName==="ChannelListTextChannelContextMenu");u.patch(M.after("default",l,([t],i)=>{const r=Object.values(t.guild.roles).map(s=>{if(!~Object.keys(t.channel.permissionOverwrites).indexOf(s.id))return;const n={...s};return n.permissions|=t.channel.permissionOverwrites[s.id].allow,n.permissionsDeny=t.channel.permissionOverwrites[s.id].deny,n}).filter(Boolean).reduce((s,n)=>Object.assign(s,{[n.id]:n}),{});return i?.props?.children?.splice(1,0,e.React.createElement(e.React.Fragment,null,e.React.createElement(p.MenuSeparator,null),e.React.createElement(p.MenuItem,{label:"View Permissions",id:"permissions",action:()=>{x(s=>e.React.createElement(m,{event:s,roles:r}))}}))),i}))};var z=()=>({onLoad(){S(),L(),v()},onUnload(){u.unpatchAll()}});return z})(cumcord.patcher,cumcord.modules.common,cumcord.modules.webpack,cumcord.ui.components);
